import Head from "next/head";
import Card from "../components/card";

export async function getStaticProps() {
  // Fetch data from external API
  const res = await fetch(`/api/car-api`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Card />
    </div>
  );
}
